import { Button, Card, Col, Container, ListGroup, Row } from 'react-bootstrap'
import { useExtensions } from '../hooks/useExtensions.ts'
import { MarketplaceExtension } from '../types'
import { Link } from 'react-router-dom'
import '../components/css/style.css'
import ExtensionCard from '../components/ExtensionCard.tsx'

export function HomeScreen() {

  const { extensions, isGettingExtensions, isErrorGettingExtensions } = useExtensions('')

  return (
    <Container className="my-4">
      <Row className="text__center">
        <Col className="col-12 col-sm-12 col-md-6 text-center">
          <img src="/travel.jpg" alt="Your travel buddy" className="img-fluid rounded image__size shadow" />
          <p className="fst-italic"><small>This image was generated by Microsoft CoPilot.</small></p>
        </Col>
        <Col className="col-12 col-sm-12 col-md-6 text-center">
          <h1 className="fw-bold">Your travel knowledge buddy</h1>
          <p>Get ready-to-use knowledge from contributors all around the world.</p>
          <Button className="btn-custom" href={'https://play.google.com/store/apps/details?id=io.osta'}>Download the app
            for free</Button>
          <Button className="btn-custom" href={'https://github.com/BauwenDR/osta'}>
            Contribute
          </Button>
        </Col>
      </Row>

      <ListGroup className="my-5">
        <Row>
          <Col className="p-1 col-12 col-sm-12 col-md-4 rounded">
            <Card body className="shadow">
              <h5 className="fw-bold"><i className="bi bi-code icon" /> Open Source</h5>
              <p>Access reliable travel information from our open-source community.</p>
            </Card>
          </Col>
          <Col className="p-1 col-12 col-sm-12 col-md-4 rounded">
            <Card body className="shadow">
              <h5 className="fw-bold"><i className="bi bi-globe icon" /> Offline Usage</h5>
              <p>Explore landmarks without the need for an internet connection.</p>
            </Card>
          </Col>
          <Col className="p-1 col-12 col-sm-12 col-md-4 rounded">
            <Card body className="shadow">
              <h5 className="fw-bold"><i className="bi bi-ban icon" /> No Ads</h5>
              <p>Enjoy an ad-free experience while discovering new destinations.</p>
            </Card>
          </Col>
        </Row>
      </ListGroup>
      <h3 className="font-semibold">Top 10 verified sources</h3>

      {extensions && extensions.length > 0 ? (
        <ListGroup>
          <Row>
            {extensions.slice(0, 10).map((extension: MarketplaceExtension) => (
              <Col className="p-1 col-sm-12 col-md-4 col-lg-3 rounded" key={extension.name}>
                <Link to={`/extension/${extension.id}`} className="text-decoration-none mt-2">
                  <ExtensionCard extension={extension} />
                </Link>
              </Col>
            ))}
          </Row>
        </ListGroup>
      ) : (
        <p>No sources found</p>
      )}

      {isGettingExtensions || !extensions && (
        <p className={'glow'}>Loading extensions ...</p>
      )}

      {isErrorGettingExtensions && (
        <p>Something went wrong while loading extensions</p>
      )}

    </Container>
  )
}

export default HomeScreen
