spring:
  application.name: OSTA-BackEnd

  datasource:
    url: jdbc:h2:mem:osta
    driverClassName: org.h2.Driver
    username: osta
    password: password

  jpa:
    database: h2
    defer-datasource-initialization: true
    generate-ddl: true
    hibernate:
      ddl-auto: create-drop
    open-in-view: false
    show-sql: true
    properties:
      hibernate.hibernate.dialect: H2SqlDialect

osta:
  data-url: https://raw.githubusercontent.com/OSTA-group/osta-extensions/refs/heads/main/extensions.json
